import JSZip from 'jszip'
import type {
  FreeZipParams,
  PremiumZipParams,
  ZipResult,
} from './zipGeneration.types'
import type { FaviconFormat } from './faviconGeneration.types'

// === INTERNAL HELPERS ===

async function fetchICOFromAPI(sourceImage: string): Promise<Blob | null> {
  try {
    // Convert base64/dataURL to Blob for FormData
    const response = await fetch(sourceImage)
    const blob = await response.blob()

    const formData = new FormData()
    formData.append('file', blob, 'favicon.png')

    const icoResponse = await fetch('/api/favicon/ico', {
      method: 'POST',
      body: formData,
    })

    if (icoResponse.ok) {
      return await icoResponse.blob()
    }
    return null
  } catch {
    return null
  }
}

function generateSnippetHTML(isPremium: boolean): string {
  const basic = `<!--
  FAVICONFORGE - FAVICON IMPLEMENTATION
  =====================================

  Copy everything below into your HTML <head> tag.

  Generated by FaviconForge (https://faviconforge.com)
-->

<!-- Basic Favicons -->
<link rel="icon" type="image/x-icon" href="/favicon.ico">
<link rel="icon" type="image/png" sizes="16x16" href="/web/favicon-16x16.png">
<link rel="icon" type="image/png" sizes="32x32" href="/web/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="48x48" href="/web/favicon-48x48.png">`

  if (!isPremium) {
    return `${basic}

<!-- End FaviconForge -->`
  }

  return `${basic}

<!-- iOS - Add to Home Screen -->
<link rel="apple-touch-icon" sizes="180x180" href="/ios/apple-touch-icon.png">

<!-- Android & PWA -->
<link rel="icon" type="image/png" sizes="192x192" href="/android/icon-192.png">
<link rel="icon" type="image/png" sizes="512x512" href="/android/icon-512.png">
<link rel="manifest" href="/manifest.json">

<!-- Windows Tiles -->
<meta name="msapplication-TileImage" content="/windows/mstile-150x150.png">
<meta name="msapplication-config" content="/browserconfig.xml">

<!-- Theme Color (matches your manifest) -->
<meta name="theme-color" content="#ffffff">

<!-- End FaviconForge -->`
}

function generateREADME(): string {
  return `# FaviconForge Output

Your favicon package is ready! This ZIP contains all the files you need for a production-ready favicon implementation.

## Quick Start

1. Extract this ZIP to your project's \`public/\` folder
2. Copy the contents of \`snippet.html\` to your HTML \`<head>\` tag
3. Done!

## Folder Structure

\`\`\`
├── web/                    Basic web favicons
│   ├── favicon.ico         Multi-resolution (16, 32, 48px)
│   ├── favicon-16x16.png   Standard favicon
│   ├── favicon-32x32.png   Retina/high-DPI
│   └── favicon-48x48.png   Windows taskbar
├── ios/                    Apple devices
│   └── apple-touch-icon.png   180x180 for home screen
├── android/                Android & PWA
│   ├── icon-192.png        Standard PWA icon
│   ├── icon-512.png        Splash screen
│   ├── maskable-icon-192.png  Adaptive icon
│   └── maskable-icon-512.png  Adaptive splash
├── windows/                Windows tiles
│   └── mstile-150x150.png  Start menu tile
├── manifest.json           PWA configuration
├── browserconfig.xml       Windows tile config
├── snippet.html            Ready-to-use HTML
└── README.md               This file
\`\`\`

## Implementation Details

### Basic Favicons (web/)
Place \`favicon.ico\` at your site root. Modern browsers also use the PNG versions.

### iOS (ios/)
The \`apple-touch-icon.png\` appears when users add your site to their home screen.

### Android & PWA (android/)
These icons are used for Android home screen and PWA installations. The maskable variants ensure your icon looks great in any shape container.

### Windows (windows/)
The \`mstile-150x150.png\` is used in Windows Start menu tiles.

### Configuration Files
- \`manifest.json\`: Place at site root, referenced in HTML
- \`browserconfig.xml\`: Place at site root, Windows will find it automatically

## Troubleshooting

**Icons not showing?**
- Clear browser cache (Ctrl+F5)
- Verify files are in correct location
- Check browser DevTools Network tab for 404 errors

**PWA not installing?**
- Ensure manifest.json is at root and accessible
- Site must be served over HTTPS
- Check Chrome DevTools > Application > Manifest for errors

---

Generated by FaviconForge
https://faviconforge.com
`
}

function determineFilePath(format: FaviconFormat): string {
  if (format.name.includes('apple-touch')) {
    return `ios/${format.name}`
  }
  if (format.name.startsWith('icon-') || format.name.includes('maskable')) {
    return `android/${format.name}`
  }
  if (format.name.includes('mstile')) {
    return `windows/${format.name}`
  }
  return `web/${format.name}`
}

// === PUBLIC API ===

export async function generateFreeZip(
  params: FreeZipParams,
): Promise<ZipResult> {
  const { formats, sourceImage } = params
  const zip = new JSZip()
  const warnings: string[] = []

  // 1. Fetch ICO from API
  const icoBlob = await fetchICOFromAPI(sourceImage)
  if (icoBlob) {
    zip.file('web/favicon.ico', icoBlob)
  } else {
    warnings.push('ico_generation_failed')
  }

  // 2. Add PNG formats (filter only free tier: 16, 32, 48)
  const freeFormats = formats.filter((format) => format.tier === 'free')
  for (const format of freeFormats) {
    zip.file(`web/${format.name}`, format.blob)
  }

  // 3. Add snippet.html with full instructions
  const snippet = generateSnippetHTML(false)
  zip.file('snippet.html', snippet)

  // 4. Generate ZIP
  const blob = await zip.generateAsync({ type: 'blob' })

  return {
    blob,
    warnings,
    filename: `faviconforge-${Date.now()}.zip`,
  }
}

export async function generatePremiumZip(
  params: PremiumZipParams,
): Promise<ZipResult> {
  const { formats, sourceImage, manifest, browserConfig } = params
  const zip = new JSZip()
  const warnings: string[] = []

  // 1. Fetch ICO from API
  const icoBlob = await fetchICOFromAPI(sourceImage)
  if (icoBlob) {
    zip.file('web/favicon.ico', icoBlob)
  } else {
    warnings.push('ico_generation_failed')
  }

  // 2. Add ALL formats to their proper folders
  for (const format of formats) {
    const path = determineFilePath(format)
    zip.file(path, format.blob)
  }

  // 3. Add metadata files at root
  zip.file('manifest.json', manifest)
  zip.file('browserconfig.xml', browserConfig)

  // 4. Add snippet.html with full instructions
  const snippet = generateSnippetHTML(true)
  zip.file('snippet.html', snippet)

  // 5. Add README.md
  const readme = generateREADME()
  zip.file('README.md', readme)

  // 6. Generate ZIP
  const blob = await zip.generateAsync({ type: 'blob' })

  return {
    blob,
    warnings,
    filename: `faviconforge-${Date.now()}.zip`,
  }
}
